scraper_languages:
  - english
  - french
  - italian

stop_chars:
  ᵊ̰̚˞͡ˀ̪ʔʰ˩˥ʲ̟̯̬ˠ̞ʷʱ̝ˁ̻ǀˑ̥̹ˢ̺ː̈

separators:
  .ˈˌ-

vowels:
  iyɨʉɯuɪʏɪʊeøɘɵɤoe̞ø̞əɤ̞o̞ɛœɜɞʌɔæɐaɶäɑɒ


# For use with pyphen
hyphenation_dict:
  english: en
  french: fr

ipa_hyphenation_dict:
  english: ipa_en
  french: ipa_fr

server_url:
  http://127.0.0.1:5001

debug_url:
  http://127.0.0.1:5000

simplifying:
  english:
    ä: a
    ɟ: ɡ
    á: a
    ɚ: əɹ
    ʍ: w
    ɝ: əɹ
    ɘ: ɪ
    õ: ɔn
    ɱ: m
    œ: ""
    ʋ: w
    ɯ: ə
    ɻ: ɹ
    ɧ: ʃ
    ɬ: l
    ã: a
    ɕ: ʃ
    ɲ: nj
    ç: h
    ẽ: e
    ɦ: h
    g: ɡ
    ĭ: ɪ
    ĩ: ɪ
    ǐ: ɪ
    ʏ: ʊ
    χ: x
    ŏ: ə
    ɥ: ju
    ɵ: ɔ
    ʎ: j
    ʝ: j
    έ: e
    n̩: n
    l̩: l
    ̩: ''
    g: ɡ
    ʀ: ɹ
    ̜: ''
    ⁓: ' '
    ~: ' '
    ̠: ''
    û: ʌ
    ˡ: ''
    ê: e
    ʕ: ''
    ̆: ''
    ̊: ''
    ‘: ''
    ɽ: r
    '|': ''


  french:
    a: a