FROM ubuntu:17.10

MAINTAINER Ludovico Altana "ludoalta@gmail.com"

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
#COPY /src /app/src

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY . /app

EXPOSE 5000

ENTRYPOINT [ "python3" ]

CMD [ "debug.py" ]

#ENTRYPOINT [ "ls" ]

#CMD [ "-la" ]